# -*- coding: utf-8 -*-
"""LaunguageTranslationTool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105Us170NcU-MJ6UtWv3c_XduXZpVWgP3
"""

!pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118

! pip install transformers ipywidgets gradio --upgrade

! pip install gradio

import  gradio as gr
from transformers import pipeline

translation_pipline = pipeline('translation_en_to_de')

result = translation_pipline('I love Coading')

result[0]['translation_text']

def tarnslate_transfromers(from_text):
  result = translation_pipline(from_text)
  return result[0]['translation_text']

tarnslate_transfromers('My name is Jack')

interface = gr.Interface(fn = tarnslate_transfromers,
                         inputs=gr.Textbox(lines=2, placeholder = "text to translate"), 
                         outputs = 'text')

interface.launch()

