# -*- coding: utf-8 -*-
"""CahtBotFor_FAQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xeIW1lXDBzzJYOosHyHmxuZABC-FoSW
"""

# nesseary Library
import io
import random
import string
import warnings
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.stem import WordNetLemmatizer
import warnings
warnings.filterwarnings('ignore')
! pip install nltk

# import nltk
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('popular', quiet=True)

# run the file into colab
f = open('/content/active learning.txt','r',errors = 'ignore')
raw = f.read()
raw = raw.lower()

# Tokenizar
sent_tokens = nltk.sent_tokenize(raw)
word_tokens = nltk.word_tokenize(raw)

# Preprocessing
lemma = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return [lemma.lemmatize(token) for token in tokens]
remoe_punc = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remoe_punc)))

# Greeting
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey")
GREETING_RESPONSES = ["hi", "hey", "nods", "hi there", "hello", "I am glad! You are talking to me"]
def greeting(sentence):
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

def response(user_response):
  Gaadha_response = ''
  sent_tokens.append(user_response)
  TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
  tfidf = TfidfVec.fit_transform(sent_tokens)
  vals = cosine_similarity(tfidf[-1], tfidf)
  idx = vals.argsort()[0][-2]
  flat = vals.flatten()
  flat.sort()
  req_tfidf = flat[-2]
  if(req_tfidf==0):
    Gaadha_response = Gaadha_response+"I am sorry! I don't understand you"
    return Gaadha_response
  else:
    Gaadha_response = Gaadha_response+sent_tokens[idx]
    return Gaadha_response

flag = True
print("Gaadha: My name is Gaadha. Let's have a conversation!  if you want to exit any time, just type Bye!")
while (flag == True):
  user_response = input()
  user_response = user_response.lower()
  if (user_response != 'bye'):
    if (user_response == 'thanks' or user_response == 'thank you'):
      flag = False
      print("Gaadha: You are welcome..")
    else:
      if (greeting(user_response) != None):
        print("Gaadha: " + greeting(user_response))
      else:
        print("Gaadha: ", end="")
        print(response(user_response))
        sent_tokens.remove(user_response)
  else:
    flag = False
    print("Gaadha: Bye! take care..")



